---
- name: Install qemu latest guet agent
  hosts: "*"
  tasks:
    - name: install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: yes
      become: true
    - name: install tree
      apt:
        name: tree
        state: present
        update_cache: yes
      become: true
    - name: install mlocate
      apt:
        name: mlocate
        state: present
        update_cache: yes
      become: true
    - name: install htop
      apt:
        name: htop
        state: present
        update_cache: yes
      become: true
    - name: install ntp
      apt:
        name: ntp
        state: present
        update_cache: yes
      become: true
